[build]
builder = "NIXPACKS"
nixpacksPlan = {"providers":["...","java"]}

[deploy]
runtime = "V2"
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10